
import javax.swing.*;
import javax.swing.JTextField;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author krishna
 */
public class xyz extends javax.swing.JFrame {

    /**
     * Creates new form xyz
     */
    public xyz() {
        initComponents();
        
        //contentPane.setVisible(true);
        in();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void in(){
        contentPane = new JPanel();
		contentPane.setForeground(new Color(0, 0, 128));
		contentPane.setBackground(Color.WHITE);
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		setContentPane(contentPane);
		contentPane.setLayout(new CardLayout(0, 0));
        JPanel panel_2 = new JPanel();
		panel_2.setBackground(java.awt.Color.WHITE);
		contentPane.add(panel_2, "name_667146104315988");
		panel_2.setLayout(null);
		
		textField = new JTextField();
                
		textField.setBounds(219, 133, 250, 46);
		panel_2.add(textField);
		textField.setColumns(10);
		
		textField_1 = new JTextField();
		textField_1.setBounds(220, 263, 249, 46);
		panel_2.add(textField_1);
		textField_1.setColumns(10);
		
		JLabel lblNewLabel_8 = new JLabel("ORDER_ID:");
		lblNewLabel_8.setFont(new Font("Tahoma", Font.BOLD, 20));
		lblNewLabel_8.setBounds(33, 140, 127, 22);
		panel_2.add(lblNewLabel_8);
		
		JLabel lblNewLabel_9 = new JLabel("CUSTOMER_ID:");
		lblNewLabel_9.setFont(new Font("Tahoma", Font.BOLD, 20));
		lblNewLabel_9.setBounds(33, 269, 177, 40);
		panel_2.add(lblNewLabel_9);
		
		JLabel lblArtid = new JLabel("ART_ID:");
		lblArtid.setFont(new Font("Tahoma", Font.BOLD, 20));
		lblArtid.setBounds(737, 31, 177, 40);
		panel_2.add(lblArtid);
		
		JLabel lblPrice = new JLabel("PRICE:");
		lblPrice.setFont(new Font("Tahoma", Font.BOLD, 20));
		lblPrice.setBounds(737, 114, 177, 40);
		panel_2.add(lblPrice);
		
		price = new JTextField();
		price.setColumns(10);
		price.setBounds(888, 116, 249, 46);
		panel_2.add(price);
		
		a_id = new JTextField();
		a_id.setColumns(10);
		a_id.setBounds(888, 33, 249, 46);
		panel_2.add(a_id);
		
		JTable table = new JTable();
		table.setBackground(Color.WHITE);
		
		Object[] colomns = {"ART NAME","PRICE"};
		table.setFont(new Font("Tahoma", Font.PLAIN, 20));
		DefaultTableModel model = new DefaultTableModel();
		model.setColumnIdentifiers(colomns);
		table.setModel(model);
		panel_2.add(table);
		
		
		JScrollPane scrollPane =new JScrollPane(table);
		scrollPane.setBounds(737, 205, 509, 222);
		panel_2.add(scrollPane);
		
		JButton btnAdd = new JButton("ADD");
		btnAdd.setBackground(Color.WHITE);
		Object[]row =new Object[1];
		btnAdd.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
				
			
				row[0]=price.getText();
				model.addRow(row);
			}
			
		});
		btnAdd.setFont(new Font("Tahoma", Font.PLAIN, 18));
		btnAdd.setBounds(1184, 80, 111, 39);
		panel_2.add(btnAdd);
		
		JLabel lblDate = new JLabel("DATE:");
		lblDate.setFont(new Font("Tahoma", Font.BOLD, 20));
		lblDate.setBounds(33, 388, 127, 22);
		panel_2.add(lblDate);
		
		textField_2 = new JTextField();
		textField_2.setColumns(10);
		textField_2.setBounds(221, 381, 249, 46);
		panel_2.add(textField_2);
		
		JButton btnDone = new JButton("DONE");
		btnDone.setFont(new Font("Tahoma", Font.PLAIN, 18));
		btnDone.setBackground(Color.WHITE);
		btnDone.setBounds(908, 472, 212, 39);
		panel_2.add(btnDone);
		
		textField_3 = new JTextField();
		textField_3.setBounds(888, 567, 249, 46);
		panel_2.add(textField_3);
		textField_3.setColumns(10);
		
		JLabel lblTotal = new JLabel("TOTAL:");
		lblTotal.setFont(new Font("Tahoma", Font.BOLD, 20));
		lblTotal.setBounds(737, 567, 177, 40);
		panel_2.add(lblTotal);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(xyz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(xyz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(xyz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(xyz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new xyz().setVisible(true);
                
            }
        });
    }
public static javax.swing.JTextField textField;
private javax.swing.JTextField textField_1;
private javax.swing.JTextField price;
private javax.swing.JTextField textField_2;
private JTextField a_id;
private JTextField textField_3  ;
private JPanel contentPane;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
